import type { Timestamp } from 'firebase/firestore'
import type { BaseDoc } from './common'

export type TaskPriority = 'low' | 'normal' | 'high' | 'urgent'

export type TaskStatus =
  | 'todo'
  | 'in_progress'
  | 'review'
  | 'waiting_client'
  | 'done'
  // Onboarding board stages (see TaskBoard) — a separate vocabulary from the
  // 5 generic ones above, used only by tasks with board: 'onboarding'.
  | 'new_client'
  | 'onboarding'
  | 'briefing'
  | 'access_setup'
  | 'planning'
  | 'active'

/** Which workflow a task belongs to — drives the status vocabulary shown in
 *  TaskDrawer/TaskFormModal (see ONBOARDING_BOARD_STATUS_ORDER /
 *  GENERIC_BOARD_STATUS_ORDER below). Optional — tasks outside these 3 flows
 *  (ex: Ativação/Materiais de Social Media) just use the generic statuses. */
export type TaskBoard = 'onboarding' | 'paid_traffic' | 'cs'

export const TASK_BOARD_LABEL: Record<TaskBoard, string> = {
  onboarding: 'Onboarding',
  paid_traffic: 'Tráfego Pago',
  cs: 'CS & Relacionamento',
}

/** Column order for the Onboarding board — status values exclusive to
 *  board: 'onboarding' tasks. */
export const ONBOARDING_BOARD_STATUS_ORDER: TaskStatus[] = [
  'new_client',
  'onboarding',
  'briefing',
  'access_setup',
  'planning',
  'active',
]

/** Column order for the Tráfego Pago and CS & Relacionamento boards — the
 *  generic vocabulary minus "Revisão", which doesn't apply to either flow. */
export const GENERIC_BOARD_STATUS_ORDER: TaskStatus[] = ['todo', 'in_progress', 'waiting_client', 'done']

/** First column a freshly created task for a given board lands on. */
export const FIRST_BOARD_STATUS: Record<TaskBoard, TaskStatus> = {
  onboarding: 'new_client',
  paid_traffic: 'todo',
  cs: 'todo',
}

export interface ChecklistItem {
  id: string
  text: string
  done: boolean
}

export type RecurrenceFrequency = 'weekly' | 'monthly'

export interface TaskRecurrence {
  frequency: RecurrenceFrequency
  /** 0=domingo … 6=sábado — only for 'weekly' */
  weekday?: number
  /** 1-31 — only for 'monthly' */
  dayOfMonth?: number
}

/** Identifies a task's position in the automatic client-onboarding workflow
 *  (see clientWorkflowTemplates.ts) — set only on auto-generated tasks.
 *  When a task carrying one of these is marked "done", the next step(s) of
 *  its sequence are created automatically; terminal/recurring steps (the
 *  weekly/monthly ones) don't chain any further. */
export type WorkflowStepKey =
  | 'pt_onboarding_bruno'
  | 'pt_onboarding_janilson'
  | 'pt_briefing'
  | 'pt_planning'
  | 'pt_trafego_semanal'
  | 'pt_trafego_mensal'
  | 'pt_cs_semanal'
  | 'pt_cs_mensal'
  | 'sm_ativacao'
  | 'sm_producao'
  | 'sm_aprovacao'
  | 'sm_cs_semanal'
  | 'sm_cs_mensal'

export interface Task extends BaseDoc {
  title: string
  description?: string
  clientId?: string
  assignedTo?: string
  dueDate?: Timestamp | null
  priority: TaskPriority
  status: TaskStatus
  checklist: ChecklistItem[]
  /** manual sort order within a list/board */
  order: number
  /** links a task to a content piece when it belongs to a social media production flow */
  contentId?: string
  /** Marks this task as recurring. There's no backend scheduler in this project
   *  (Firestore + client only, no Cloud Functions) — recurrence is informational:
   *  the drawer offers a "duplicate next occurrence" action instead of an
   *  automatic job. */
  recurrence?: TaskRecurrence | null
  /** Which workflow this task belongs to, if any (see TaskBoard) — drives the
   *  status vocabulary shown in TaskDrawer/TaskFormModal. */
  board?: TaskBoard
  /** See WorkflowStepKey. */
  workflowStep?: WorkflowStepKey | null
  /** Only set on the 'pt_onboarding_janilson' step — date/time of the
   *  briefing meeting the CS schedules with the client. Required before that
   *  task can be marked done; saving it creates a Calendário event and
   *  notifies the whole team (see clientWorkflowTemplates.ts). */
  briefingMeetingDate?: Timestamp | null
  briefingMeetingTime?: string
  /** Bookkeeping for the client-side due-date notification sweep (see
   *  taskService.runTaskDueDateSweep) — this project has no backend
   *  scheduler, so overdue/reminder notifications are generated by whichever
   *  teammate's browser has the app open when a due date rolls over. Set
   *  once so the same task never notifies twice. */
  overdueNotifiedAt?: Timestamp | null
  reminderNotifiedAt?: Timestamp | null
}

export const TASK_STATUS_LABEL: Record<TaskStatus, string> = {
  todo: 'A Fazer',
  in_progress: 'Em Andamento',
  review: 'Revisão',
  waiting_client: 'Aguardando Cliente',
  done: 'Concluído',
  new_client: 'Novo Cliente',
  onboarding: 'Onboarding',
  briefing: 'Briefing',
  access_setup: 'Acessos',
  planning: 'Planejamento',
  active: 'Ativo',
}

export const TASK_STATUS_ORDER: TaskStatus[] = [
  'todo',
  'in_progress',
  'review',
  'waiting_client',
  'done',
]

export const TASK_PRIORITY_LABEL: Record<TaskPriority, string> = {
  low: 'Baixa',
  normal: 'Normal',
  high: 'Alta',
  urgent: 'Urgente',
}

export const TASK_PRIORITY_COLOR: Record<TaskPriority, string> = {
  low: 'badge-priority-normal',
  normal: 'badge-priority-normal',
  high: 'badge-priority-high',
  urgent: 'badge-priority-high',
}

const WEEKDAY_LABEL = ['domingo', 'segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado']

export function formatRecurrence(recurrence: TaskRecurrence): string {
  if (recurrence.frequency === 'weekly') {
    return `Semanal — toda ${WEEKDAY_LABEL[recurrence.weekday ?? 1]}`
  }
  return `Mensal — todo dia ${recurrence.dayOfMonth ?? 1}`
}

/** Next date matching the recurrence rule, on or after `after`. Used both to
 *  seed the first occurrence at client creation and, later, by the drawer's
 *  "duplicate next occurrence" action (see recurrence comment on Task). */
export function nextRecurrenceDate(recurrence: TaskRecurrence, after: Date = new Date()): Date {
  const start = new Date(after.getFullYear(), after.getMonth(), after.getDate())

  if (recurrence.frequency === 'weekly') {
    const weekday = recurrence.weekday ?? 1
    const diff = (weekday - start.getDay() + 7) % 7
    start.setDate(start.getDate() + diff)
    return start
  }

  const day = recurrence.dayOfMonth ?? 1
  const candidate = new Date(start.getFullYear(), start.getMonth(), day)
  if (candidate < start) candidate.setMonth(candidate.getMonth() + 1)
  return candidate
}
