import type { ReactNode } from 'react'
import { useDroppable } from '@dnd-kit/core'

export function KanbanColumn({
  id,
  label,
  count,
  accent = 'bg-slate-300',
  accentColor,
  children,
}: {
  id: string
  label: string
  count: number
  /** Tailwind bg-* class — text accent is derived from it (bg- → text-).
   *  Ignored when `accentColor` is given. */
  accent?: string
  /** Raw hex, applied via inline style — use this instead of `accent` for a
   *  palette not already baked into the Tailwind theme (an arbitrary-value
   *  class built from a runtime string, e.g. `` `bg-[${hex}]` ``, never gets
   *  generated by Tailwind's static scanner, so it would silently do
   *  nothing). */
  accentColor?: string
  children: ReactNode
}) {
  const { setNodeRef, isOver } = useDroppable({ id })
  const textAccent = accent.replace('bg-', 'text-')

  return (
    <div
      ref={setNodeRef}
      className={`flex min-h-0 w-72 min-w-[280px] shrink-0 flex-col rounded-xl bg-slate-50 p-3 ${
        isOver ? 'ring-2 ring-brand-300' : ''
      }`}
    >
      <div className="mb-2 flex items-center gap-2 px-1">
        <span className={accentColor ? 'h-2 w-2 rounded-full' : `h-2 w-2 rounded-full ${accent}`} style={accentColor ? { backgroundColor: accentColor } : undefined} />
        <p
          className={accentColor ? 'text-[11px] font-bold uppercase tracking-wide' : `text-[11px] font-bold uppercase tracking-wide ${textAccent}`}
          style={accentColor ? { color: accentColor } : undefined}
        >
          {label}
        </p>
        <span className="ml-auto rounded-full bg-slate-200/70 px-1.5 py-0.5 text-[10px] font-medium text-slate-500">
          {count}
        </span>
      </div>
      <div className="min-h-[40px] flex-1 overflow-y-auto px-0.5 pb-1">{children}</div>
    </div>
  )
}
